# Generated by Django 5.1 on 2024-08-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('part', models.CharField(choices=[('n.', 'noun'), ('v.', 'verb'), ('adj', 'adjective')], max_length=100)),
                ('definition', models.TextField()),
                ('example', models.TextField()),
                ('collocation', models.CharField(max_length=250)),
            ],
        ),
    ]
